name: Ejecutar Oráculo Soberano

on: [push]

jobs:
  ejecucion-robusta:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Ejecutar motor
        env:
          # Esta línea es el puente: toma el secreto y lo inyecta como variable de entorno
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          python3 motor_dpt_soberano.py
